project_id = "evfnizkgmjiioktxkple"

[functions.negotiate]
verify_jwt = false

[functions.sentinel-chat]
verify_jwt = false

[functions.send-certificate]
verify_jwt = false

[functions.verify-setup-secret]
verify_jwt = false
